# Generated by Django 2.2.28 on 2024-03-01 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commentTime',
            new_name='comment_time',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='userOwner',
            new_name='user_owner',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='aboutTime',
            new_name='about_time',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='postTime',
            new_name='post_time',
        ),
    ]
