# Generated by Django 2.2.28 on 2024-03-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20240301_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='about_time',
            field=models.DateField(null=True),
        ),
    ]
