# Generated by Django 2.2.28 on 2024-03-06 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_postreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postreport',
            old_name='post',
            new_name='post_id',
        ),
        migrations.RenameField(
            model_name='postreport',
            old_name='user',
            new_name='reporter',
        ),
    ]
