# Generated by Django 2.2.28 on 2024-03-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20240301_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='username_slug',
            new_name='slug',
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='about_time',
            field=models.DateField(),
        ),
    ]
