# Generated by Django 2.2.28 on 2024-03-06 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20240306_1454'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postreport',
            options={'verbose_name_plural': 'Post Reports'},
        ),
    ]
