# Generated by Django 2.2.28 on 2024-03-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20240305_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='user_profile',
        ),
        migrations.AlterField(
            model_name='post',
            name='about_time',
            field=models.DateField(blank=True),
        ),
    ]
