# Generated by Django 2.2.28 on 2024-03-06 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20240306_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='about_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
