# Generated by Django 2.2.28 on 2024-03-06 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20240306_2136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='user_profile',
        ),
    ]
